name: Main

on:
  push:
    branches:
      - main
jobs:
  tikui:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Validate project
        uses: ./.github/actions/validate

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Deploy Storybook
        run: |
          git config --local user.email "support+actions@github.com"
          git config --local user.name "github-actions-bot"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build package
      #   run: pnpm build

      # - name: Release package
      #   run: pnpm semantic-release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     HUSKY: 0
